"""use sast time default

Revision ID: cd6dc97e784b
Revises: 456b5afbc208
Create Date: 2025-12-11 16:09:36.569027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6dc97e784b'
down_revision = '456b5afbc208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

