"""sub categories + emergency savings

Revision ID: 14bffadefdac
Revises: cd6dc97e784b
Create Date: 2025-12-24 17:39:16.932145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bffadefdac'
down_revision = 'cd6dc97e784b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'group')
    # ### end Alembic commands ###

