"""add emergency RA columns to budget table

Revision ID: 3f8b595bf8ea
Revises: f394d52ecd8e
Create Date: 2025-12-26 18:41:04.288927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8b595bf8ea'
down_revision = 'f394d52ecd8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('current_ra_value', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('monthly_ra_contribution', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'monthly_ra_contribution')
    op.drop_column('budgets', 'current_ra_value')
    # ### end Alembic commands ###

