"""create separate tables for emergency savings and ra

Revision ID: 58d25008c570
Revises: 3f8b595bf8ea
Create Date: 2025-12-29 13:02:41.798932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d25008c570'
down_revision = '3f8b595bf8ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_fund', sa.Float(), nullable=True),
    sa.Column('monthly_deposit', sa.Float(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_months', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_emergency_savings_id'), 'emergency_savings', ['id'], unique=False)
    op.create_table('retirement_annuities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('monthly_contribution', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_retirement_annuities_id'), 'retirement_annuities', ['id'], unique=False)
    op.drop_column('budgets', 'emergency_target_value')
    op.drop_column('budgets', 'emergency_target_months')
    op.drop_column('budgets', 'current_emergency_fund')
    op.drop_column('budgets', 'emergency_target_type')
    op.drop_column('budgets', 'current_ra_value')
    op.drop_column('budgets', 'monthly_ra_contribution')
    op.drop_column('budgets', 'monthly_emergency_deposit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('monthly_emergency_deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('monthly_ra_contribution', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('current_ra_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('emergency_target_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('current_emergency_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('emergency_target_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('emergency_target_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_retirement_annuities_id'), table_name='retirement_annuities')
    op.drop_table('retirement_annuities')
    op.drop_index(op.f('ix_emergency_savings_id'), table_name='emergency_savings')
    op.drop_table('emergency_savings')
    # ### end Alembic commands ###

