"""RA history table

Revision ID: 28dc4dd0e8d2
Revises: eb03699a2c48
Create Date: 2026-02-03 20:17:41.811021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28dc4dd0e8d2'
down_revision = 'eb03699a2c48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ra_value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('total_contributions', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'record_date', name='uq_ra_value_history_user_record_date')
    )
    op.create_index(op.f('ix_ra_value_history_id'), 'ra_value_history', ['id'], unique=False)
    op.create_index(op.f('ix_ra_value_history_record_date'), 'ra_value_history', ['record_date'], unique=False)
    op.create_index(op.f('ix_ra_value_history_user_id'), 'ra_value_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ra_value_history_user_id'), table_name='ra_value_history')
    op.drop_index(op.f('ix_ra_value_history_record_date'), table_name='ra_value_history')
    op.drop_index(op.f('ix_ra_value_history_id'), table_name='ra_value_history')
    op.drop_table('ra_value_history')
    # ### end Alembic commands ###

