"""update RA tables

Revision ID: 7e052336f872
Revises: 28dc4dd0e8d2
Create Date: 2026-02-03 20:29:45.945554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e052336f872'
down_revision = '28dc4dd0e8d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ra_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contribution_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ra_contributions_contribution_date'), 'ra_contributions', ['contribution_date'], unique=False)
    op.create_index(op.f('ix_ra_contributions_id'), 'ra_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_ra_contributions_user_id'), 'ra_contributions', ['user_id'], unique=False)
    op.drop_column('ra_value_history', 'total_contributions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ra_value_history', sa.Column('total_contributions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ra_contributions_user_id'), table_name='ra_contributions')
    op.drop_index(op.f('ix_ra_contributions_id'), table_name='ra_contributions')
    op.drop_index(op.f('ix_ra_contributions_contribution_date'), table_name='ra_contributions')
    op.drop_table('ra_contributions')
    # ### end Alembic commands ###

