"""add_transaction_category_to_budget_category

Revision ID: 34cd08c72a56
Revises: 38bf4675e638
Create Date: 2026-02-22 15:39:08.827940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cd08c72a56'
down_revision = '38bf4675e638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('transaction_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'transaction_category')
    # ### end Alembic commands ###

