"""remove_group_from_budget_category

Revision ID: 28c946322432
Revises: 83ec82edcf8e
Create Date: 2026-02-22 16:06:29.321180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c946322432'
down_revision = '83ec82edcf8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

