"""add_budget_period_start_day

Revision ID: af6a400f9228
Revises: 76b3967efcf1
Create Date: 2026-02-23 18:42:31.595782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6a400f9228'
down_revision = '76b3967efcf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('budget_period_start_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'budget_period_start_day')
    # ### end Alembic commands ###

