"""add manual payslip table

Revision ID: 7a44be3ec5a2
Revises: 131155c7968f
Create Date: 2026-02-24 19:10:12.524963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a44be3ec5a2'
down_revision = '131155c7968f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

