"""add_has_investec_account_to_users

Revision ID: 131155c7968f
Revises: 1e0f0e4a8813
Create Date: 2026-02-24 13:55:00.728429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131155c7968f'
down_revision = '1e0f0e4a8813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_investec_account', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_investec_account')
    # ### end Alembic commands ###

