"""add_budget_period_start_daymake

Revision ID: 1e0f0e4a8813
Revises: af6a400f9228
Create Date: 2026-02-23 18:46:59.064228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0f0e4a8813'
down_revision = 'af6a400f9228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

