"""add_fund_source_to_emergency_savings

Revision ID: 38bf4675e638
Revises: 4e5c4f47f67f
Create Date: 2026-02-22 15:08:07.835553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bf4675e638'
down_revision = '4e5c4f47f67f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_savings', sa.Column('fund_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_savings', 'fund_source')
    # ### end Alembic commands ###

