"""add_cost_basis_to_bond_holdings

Revision ID: 456b5afbc208
Revises: 8dbccf986b0e
Create Date: 2025-12-11 12:16:06.405713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456b5afbc208'
down_revision = '8dbccf986b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bond_holdings', sa.Column('cost_basis', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bond_holdings', 'cost_basis')
    # ### end Alembic commands ###

