"""add payslip tables

Revision ID: 6c55ad7380c8
Revises: f46ac204041b
Create Date: 2026-02-05 15:14:29.774981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c55ad7380c8'
down_revision = 'f46ac204041b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('paye', sa.Float(), nullable=True),
    sa.Column('uif_employee_portion', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('gcs_file_path', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_monthly_payslip_user_year_month')
    )
    op.create_index(op.f('ix_monthly_payslips_id'), 'monthly_payslips', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_payslips_month'), 'monthly_payslips', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_payslips_user_id'), 'monthly_payslips', ['user_id'], unique=False)
    op.create_index(op.f('ix_monthly_payslips_year'), 'monthly_payslips', ['year'], unique=False)
    op.create_table('payslip_additional_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['payslip_id'], ['monthly_payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_additional_income_id'), 'payslip_additional_income', ['id'], unique=False)
    op.create_index(op.f('ix_payslip_additional_income_payslip_id'), 'payslip_additional_income', ['payslip_id'], unique=False)
    op.create_table('payslip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payslip_id'], ['monthly_payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_items_id'), 'payslip_items', ['id'], unique=False)
    op.create_index(op.f('ix_payslip_items_payslip_id'), 'payslip_items', ['payslip_id'], unique=False)
    op.add_column('users', sa.Column('openai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'openai_api_key')
    op.drop_index(op.f('ix_payslip_items_payslip_id'), table_name='payslip_items')
    op.drop_index(op.f('ix_payslip_items_id'), table_name='payslip_items')
    op.drop_table('payslip_items')
    op.drop_index(op.f('ix_payslip_additional_income_payslip_id'), table_name='payslip_additional_income')
    op.drop_index(op.f('ix_payslip_additional_income_id'), table_name='payslip_additional_income')
    op.drop_table('payslip_additional_income')
    op.drop_index(op.f('ix_monthly_payslips_year'), table_name='monthly_payslips')
    op.drop_index(op.f('ix_monthly_payslips_user_id'), table_name='monthly_payslips')
    op.drop_index(op.f('ix_monthly_payslips_month'), table_name='monthly_payslips')
    op.drop_index(op.f('ix_monthly_payslips_id'), table_name='monthly_payslips')
    op.drop_table('monthly_payslips')
    # ### end Alembic commands ###

