"""add_excluded_to_budget_category

Revision ID: 83ec82edcf8e
Revises: 34cd08c72a56
Create Date: 2026-02-22 15:53:56.076506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ec82edcf8e'
down_revision = '34cd08c72a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('excluded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'excluded')
    # ### end Alembic commands ###

