"""add_historical_price_tracking

Revision ID: 8dbccf986b0e
Revises: cceb903f61a1
Create Date: 2025-12-11 06:51:46.809696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbccf986b0e'
down_revision = 'cceb903f61a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jse_ticker', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etf_price_history_id'), 'etf_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_etf_price_history_jse_ticker'), 'etf_price_history', ['jse_ticker'], unique=False)
    op.create_index(op.f('ix_etf_price_history_recorded_at'), 'etf_price_history', ['recorded_at'], unique=False)
    op.create_table('daily_portfolio_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('opening_value', sa.Float(), nullable=True),
    sa.Column('closing_value', sa.Float(), nullable=True),
    sa.Column('high_value', sa.Float(), nullable=True),
    sa.Column('low_value', sa.Float(), nullable=True),
    sa.Column('total_contributions', sa.Float(), nullable=True),
    sa.Column('contributions_today', sa.Float(), nullable=True),
    sa.Column('total_growth', sa.Float(), nullable=True),
    sa.Column('daily_change', sa.Float(), nullable=True),
    sa.Column('daily_change_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_portfolio_summary_date'), 'daily_portfolio_summary', ['date'], unique=False)
    op.create_index(op.f('ix_daily_portfolio_summary_id'), 'daily_portfolio_summary', ['id'], unique=False)
    op.create_index(op.f('ix_daily_portfolio_summary_user_id'), 'daily_portfolio_summary', ['user_id'], unique=False)
    op.create_table('monthly_portfolio_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('opening_value', sa.Float(), nullable=True),
    sa.Column('closing_value', sa.Float(), nullable=True),
    sa.Column('high_value', sa.Float(), nullable=True),
    sa.Column('low_value', sa.Float(), nullable=True),
    sa.Column('average_value', sa.Float(), nullable=True),
    sa.Column('total_contributions', sa.Float(), nullable=True),
    sa.Column('contributions_this_month', sa.Float(), nullable=True),
    sa.Column('total_growth', sa.Float(), nullable=True),
    sa.Column('monthly_change', sa.Float(), nullable=True),
    sa.Column('monthly_change_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_portfolio_summary_id'), 'monthly_portfolio_summary', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_portfolio_summary_month'), 'monthly_portfolio_summary', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_portfolio_summary_user_id'), 'monthly_portfolio_summary', ['user_id'], unique=False)
    op.create_index(op.f('ix_monthly_portfolio_summary_year'), 'monthly_portfolio_summary', ['year'], unique=False)
    op.create_table('portfolio_value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_contributions', sa.Float(), nullable=True),
    sa.Column('total_growth', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_value_history_id'), 'portfolio_value_history', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_value_history_recorded_at'), 'portfolio_value_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_portfolio_value_history_user_id'), 'portfolio_value_history', ['user_id'], unique=False)
    op.create_table('holding_value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('holding_id', sa.Integer(), nullable=True),
    sa.Column('jse_ticker', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('unrealized_gain', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['etf_holdings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_value_history_holding_id'), 'holding_value_history', ['holding_id'], unique=False)
    op.create_index(op.f('ix_holding_value_history_id'), 'holding_value_history', ['id'], unique=False)
    op.create_index(op.f('ix_holding_value_history_jse_ticker'), 'holding_value_history', ['jse_ticker'], unique=False)
    op.create_index(op.f('ix_holding_value_history_recorded_at'), 'holding_value_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_holding_value_history_user_id'), 'holding_value_history', ['user_id'], unique=False)
    op.add_column('etf_holdings', sa.Column('cost_basis', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etf_holdings', 'cost_basis')
    op.drop_index(op.f('ix_holding_value_history_user_id'), table_name='holding_value_history')
    op.drop_index(op.f('ix_holding_value_history_recorded_at'), table_name='holding_value_history')
    op.drop_index(op.f('ix_holding_value_history_jse_ticker'), table_name='holding_value_history')
    op.drop_index(op.f('ix_holding_value_history_id'), table_name='holding_value_history')
    op.drop_index(op.f('ix_holding_value_history_holding_id'), table_name='holding_value_history')
    op.drop_table('holding_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_user_id'), table_name='portfolio_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_recorded_at'), table_name='portfolio_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_id'), table_name='portfolio_value_history')
    op.drop_table('portfolio_value_history')
    op.drop_index(op.f('ix_monthly_portfolio_summary_year'), table_name='monthly_portfolio_summary')
    op.drop_index(op.f('ix_monthly_portfolio_summary_user_id'), table_name='monthly_portfolio_summary')
    op.drop_index(op.f('ix_monthly_portfolio_summary_month'), table_name='monthly_portfolio_summary')
    op.drop_index(op.f('ix_monthly_portfolio_summary_id'), table_name='monthly_portfolio_summary')
    op.drop_table('monthly_portfolio_summary')
    op.drop_index(op.f('ix_daily_portfolio_summary_user_id'), table_name='daily_portfolio_summary')
    op.drop_index(op.f('ix_daily_portfolio_summary_id'), table_name='daily_portfolio_summary')
    op.drop_index(op.f('ix_daily_portfolio_summary_date'), table_name='daily_portfolio_summary')
    op.drop_table('daily_portfolio_summary')
    op.drop_index(op.f('ix_etf_price_history_recorded_at'), table_name='etf_price_history')
    op.drop_index(op.f('ix_etf_price_history_jse_ticker'), table_name='etf_price_history')
    op.drop_index(op.f('ix_etf_price_history_id'), table_name='etf_price_history')
    op.drop_table('etf_price_history')
    # ### end Alembic commands ###

