"""remove old salary tables

Revision ID: 9082ea4dd696
Revises: 6c55ad7380c8
Create Date: 2026-02-08 14:46:12.125584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9082ea4dd696'
down_revision = '6c55ad7380c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_items_id'), table_name='salary_items')
    op.drop_table('salary_items')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_table('salaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('salaries_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medical_aid_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('basic_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='salaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='salaries_pkey'),
    sa.UniqueConstraint('user_id', name='salaries_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_table('salary_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_fringe', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['salary_id'], ['salaries.id'], name=op.f('salary_items_salary_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('salary_items_pkey'))
    )
    op.create_index(op.f('ix_salary_items_id'), 'salary_items', ['id'], unique=False)
    # ### end Alembic commands ###

