"""update salary table

Revision ID: b4ed53d06c71
Revises: 8502886cb1cc
Create Date: 2025-12-31 09:01:07.279786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ed53d06c71'
down_revision = '8502886cb1cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('basic_salary', sa.Float(), nullable=True))
    op.add_column('salaries', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('salary_items', sa.Column('is_fringe', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_items', 'is_fringe')
    op.drop_column('salaries', 'age')
    op.drop_column('salaries', 'basic_salary')
    # ### end Alembic commands ###

