"""add_investec_integration

Revision ID: b83471356c99
Revises: 9082ea4dd696
Create Date: 2026-02-20 16:34:28.572217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83471356c99'
down_revision = '9082ea4dd696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investec_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('investec_account_id', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('reference_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('balance_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investec_accounts_id'), 'investec_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_investec_accounts_investec_account_id'), 'investec_accounts', ['investec_account_id'], unique=True)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('time_period', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('investec_uuid', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('transaction_category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('card_number', sa.String(), nullable=True),
    sa.Column('running_balance', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ai_category_confidence', sa.Float(), nullable=True),
    sa.Column('user_corrected', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['investec_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_investec_uuid'), 'bank_transactions', ['investec_uuid'], unique=True)
    op.create_index(op.f('ix_bank_transactions_user_id'), 'bank_transactions', ['user_id'], unique=False)
    op.create_table('categorization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_from_correction', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_rules_id'), 'categorization_rules', ['id'], unique=False)
    op.create_index(op.f('ix_categorization_rules_user_id'), 'categorization_rules', ['user_id'], unique=False)
    op.add_column('users', sa.Column('investec_client_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('investec_client_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('investec_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_fund_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'investec_accounts', ['emergency_fund_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'emergency_fund_account_id')
    op.drop_column('users', 'investec_api_key')
    op.drop_column('users', 'investec_client_secret')
    op.drop_column('users', 'investec_client_id')
    op.drop_index(op.f('ix_categorization_rules_user_id'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_id'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    op.drop_index(op.f('ix_bank_transactions_user_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_investec_uuid'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_investec_accounts_investec_account_id'), table_name='investec_accounts')
    op.drop_index(op.f('ix_investec_accounts_id'), table_name='investec_accounts')
    op.drop_table('investec_accounts')
    # ### end Alembic commands ###

