"""add columns to salary table

Revision ID: db93fb3c0fde
Revises: b4ed53d06c71
Create Date: 2025-12-31 09:51:26.700462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db93fb3c0fde'
down_revision = 'b4ed53d06c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'age')
    op.add_column('salaries', sa.Column('net_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salaries', 'net_salary')
    op.add_column('budgets', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

