"""add user sheets table

Revision ID: eb03699a2c48
Revises: db93fb3c0fde
Create Date: 2026-01-01 12:23:33.738525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb03699a2c48'
down_revision = 'db93fb3c0fde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_sheets_id'), 'user_sheets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sheets_id'), table_name='user_sheets')
    op.drop_table('user_sheets')
    # ### end Alembic commands ###

