"""emergency savings

Revision ID: f394d52ecd8e
Revises: 14bffadefdac
Create Date: 2025-12-24 18:19:03.722545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f394d52ecd8e'
down_revision = '14bffadefdac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('current_emergency_fund', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('monthly_emergency_deposit', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('emergency_target_type', sa.String(), nullable=True))
    op.add_column('budgets', sa.Column('emergency_target_months', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('emergency_target_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'emergency_target_value')
    op.drop_column('budgets', 'emergency_target_months')
    op.drop_column('budgets', 'emergency_target_type')
    op.drop_column('budgets', 'monthly_emergency_deposit')
    op.drop_column('budgets', 'current_emergency_fund')
    # ### end Alembic commands ###

