"""remove current_value col from retirement_annuities

Revision ID: f46ac204041b
Revises: 7e052336f872
Create Date: 2026-02-05 09:30:38.569678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46ac204041b'
down_revision = '7e052336f872'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retirement_annuities', 'current_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_annuities', sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

